<MyLayout>
    BoxLayout:
        id: container
        orientation: "vertical"
        size: root.width, root.height
        Label:
            id: click_label
            text: "Pick Equipment"
        Spinner:
            id: spinner_id
            text: "Pick Equipment"
            values: app.r
            on_press: root.spinner_update() 
            on_text: root.spinner_clicked(spinner_id.text)
        Label:
